version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: bot
    restart: always
    env_file:
      - .env.sample
    networks:
      - app
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    env_file:
      - .env.sample
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - app
    volumes:
      - redis-data:/bitnami/redis/data
    #command: /bin/sh -c "redis-server --requirepass $${REDIS_PASS:?REDIS_PASS variable is not set}"

networks:
  app:
    driver: bridge

volumes:
  redis-data: {}

